### ISSUE TITLE
Still being maintained?

### ISSUE THREAD

**Issue by ConduciveMammal** [scandel/pdfThumbnails#1]
I've just started using this on a project and it works pretty well, I'm just wondering if it's still being maintained?  It currently breaks at pdf.js version 2.0.419 and later. Producing the error:
```
pdf.js is not loaded. Please include it before pdfThumbnails.js.
    at HTMLDocument.createPDFThumbnails
```

**Comment by scandel** [comment]
Hi, thanks for your interest. It's a really small project and I don't really need to maintain it unless there is something broken... I did not test it with pdf.js 2+, will have a look. 

About your error, do you have both files pdf.js and pdf.worker.js in the same directory, and do you load the pdf.js file in your html page ?

**Comment by ConduciveMammal** [comment]
Hey Scandel,
Ahh yeah I did wonder since I'd not seen any other issues listed.

I'm not using the worker.js as it seemed to be working fine without it, should I still be using it? Up to version 2.0.402 seems to be working fine, it's just any after that that breaks.

**Comment by scandel** [comment]
Yes, please try to use the worker.

**Comment by ConduciveMammal** [comment]
Hmmm so I added the worker for the 2.4.402 version and it seemed to make no difference. I changed the versions to the latest and it again produced the error mentioned above.
`if (typeof PDFJS === 'undefined') {`

My guess is they've changed `PDFJS` at some point so now it consistently returns `undefined`

**Comment by cffebradley** [comment]
Having the same issue.

Though I got it to work with pdfjs-1.10.100-dist.

**Comment by scandel** [comment]
Now works with PDFJS 2.0+ !

**Comment by ConduciveMammal** [comment]
Great! Thanks! Are there any noticeable changes?

**Comment by scandel** [comment]
No, it's just that the PDFJS object was renamed pdfjsLib in version 2...
