### ISSUE TITLE
Does not support absolute path

### ISSUE THREAD

**Issue by soubhikchatterjee** [scandel/pdfThumbnails#3]
I am using this in one of my project but recently noticed that it does not support absolute pdf paths.

For eg, the following works
```
<img
          class="img-responsive"
          data-pdf-thumbnail-file="diploma.pdf"
          src="pdf.png"
        />
```

But same pdf when given absolute path does not work. 
```
<img
          class="img-responsive"
          data-pdf-thumbnail-file="/var/www/html/test/pdfThumbnails/diploma.pdf"
          src="pdf.png"
        />

```

Console shows the following error:
pdfThumbnails error: could not find or open document /var/www/html/test/pdfThumbnails/diploma.pdf. Not a pdf ?

Please help!!

**Comment by scandel** [comment]
Hi, it's normal, you're on client side. It works like the html img tag, and so does not support absolute  path on the server.
