### ISSUE TITLE
Not loading thumbnail when loading pdf dynamically.

### ISSUE THREAD

**Issue by sohrabzia** [scandel/pdfThumbnails#6]
I am searching the PDF and displaying based on year but its not showing up the thumbnail. It works on the pdf which is loaded on page load. I am using rest API to fetch new searched pdf. Any solution?

**Comment by sohrabzia** [comment]
no support?

**Comment by scandel** [comment]
Hi, sorry but it does not seem to be a problem with the library. Maybe you need to do something when a load event is triggered, or something like that... difficult to say without seeing your code.

**Comment by sohrabzia** [comment]
I am just appending the image like this `<img data-pdf-thumbnail-file="/my/file.pdf" data-pdf-thumbnail-width="200">`
I am getting the data with rest API. on page load it works just fine but when I try to load the data without refreshing the page (through js), the thumbnails doesn't show up. 

there isn't much to do with this plugin as it is quite simple to add data-pdf attribute. only issue is thumbnails wont show up when pdf is displayed without page refresh.

**Comment by sohrabzia** [comment]
Fixed the issue by appending the pdf.js and pdfThumbnails library on the fly just before fetching new pdfs with half a second of timeout. its a dirty work but it works!

**Comment by eyaler** [comment]
@sohrabzia  could you please share your solution?

**Comment by sohrabzia** [comment]
> @sohrabzia could you please share your solution?

i am just appending the pdf library script links everytime there is new request.
like ` $('head').append('<script type="text/javascript" src="Link to your pdf.js file"></script>');`

**Comment by gilphilbert** [comment]
There's a more dynamic way to handle this as the library currently is:

Add your image to the DOM (using whatever framework you like). Once the new DOM node is added, simply call:
```js
createPDFThumbnails()
```

However, this is still fairly inefficient since it actually re-renders all PDFs in the DOM.
